server:
  port: 8081
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  # config druid
  datasource:
    druid:
      url: jdbc:mysql://8.130.129.206:3306/qiangke?serverTimezone=UTC
      ##url: jdbc:mysql://43.142.73.234:3306/qiangke
      username: root
      password: 568568Root@
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 100
      max-active: 1000
      min-idle: 500
      max-wait: 5000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat #配置多个英文逗号分隔

  # config redis
  redis:
    host: 8.130.129.206
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 2000
        max-idle: 200
        max-wait: 3

  # config rabbitmq
  rabbitmq:
    host: 8.130.136.61
    port: 5672
    username: root
    password: root
    virtual-host: mq_vhost  # docker容器中配置的名称
    publisher-confirms: true  #交换机是否收到消息确认
    publisher-returns: true     # 队列是否收到消息确认,默认false
    listener:
      simple:
        concurrency: 10  # 最小的消费者线程数量
        max-concurrency: 10  # 最大的消费者线程数量
        prefetch: 1  # 每个消费者最多取几个消息出队
        auto-startup: true  # 是否启动时启动容器
        default-requeue-rejected: true  # 消费失败重新进队
    template:
      retry:
        enabled: true  # 生产者入队是否重试
        initial-interval: 1000  # Duration between the first and second attempt to deliver a message.
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
      mandatory: true

#publisher-confirms：设置为true时。当消息投递到Exchange后，会回调confirm()方法进行通知生产者
#publisher-returns：设置为true时。当消息匹配到Queue并且失败时，会通过回调returnedMessage()方法返回消息
#spring.rabbitmq.template.mandatory: 设置为true时。指定消息在没有被队列接收时会通过回调returnedMessage()方法退回。

# config mybatis (http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/index.html)
mybatis:
  type-aliases-package: yiming.chris.GrabCourses.domainn
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000